title: 'Web Foundations (Canonical Lessons)'
url: 'https://ruvebal.github.io/web-atelier-udit/'
baseurl: '/web-atelier-udit'
markdown: kramdown
kramdown: { toc_levels: 2..3, footnote_backlink: '↩︎' }
theme: null
collections:
 lessons:
  output: true
  permalink: /lessons//:lang/:slug/
 bibliography:
  output: true
  permalink: /bibliography/:lang/
 methodology:
  output: true
  permalink: /methodology/:lang/
defaults:
 - scope: { path: '_lessons', type: 'lessons' }
   values:
    layout: lesson
 - scope: { path: '_bibliography', type: 'bibliography' }
   values:
    layout: bibliography
 - scope: { path: '_methodology', type: 'methodology' }
   values:
    layout: methodology
