name: Link Check

on:
 pull_request:
 push:
  branches: [main]

jobs:
 lychee:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout
     uses: actions/checkout@v4
   - name: Link check (lychee)
     id: lychee
     uses: lycheeverse/lychee-action@v1
     with:
      args: >-
       --verbose
       --no-progress
       --accept 200,429
       --exclude-mail
       --max-concurrency 8
       --retry-wait-time 2
       --timeout 20
       .
     env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

   - name: Fail on broken links
     if: ${{ steps.lychee.outputs.exit_code != 0 }}
     run: exit 1
